function love.load()
	pedra = love.graphics.newImage("pedra.png")	
	g = love.graphics.newImage("layer.png")	
player = love.graphics.newImage("purple.png")
craft4 = love.graphics.newImage("craft4.png")
	cyan = love.graphics.setColor(0, 255, 255)
	pink = love.graphics.setColor(255, 105, 180)
	   gui = love.graphics.newImage("gui.png")
   racka = love.graphics.newImage("racka.png")
   racka2 = love.graphics.newImage("mmap2.png")
   craft = love.graphics.newImage("craft.png")
   seta1 = love.graphics.newImage("seta1.png")
   seta2 = love.graphics.newImage("seta2.png")
   racka3 = love.graphics.newImage("map1_2.png")
   va = love.graphics.newImage("51.png")
   mg = love.graphics.newImage("machine gun.png")
   mag= love.graphics.newImage("mg.png")
   seta3 = love.graphics.newImage("seta3.png")
   mp21 = love.graphics.newImage("mapa_2_1.png")
    terra = love.graphics.newImage("goku.png")
    b= love.graphics.newImage("button.png")
 builder = love.graphics.newImage("builder.gif")
  crafting = love.graphics.newImage("CRAFTING TABLE.png")
end